---

stages:
  - build
  - test
  - bin

build:
  stage: build
  script:
    - make docker-build
  cache:
    paths:
      - vendor
      - bin

test:
  stage: test
  script:
    - git remote -v
    - make docker-test
  cache:
    paths:
      - vendor
      - bin

bin:
  stage: bin
  script:
    - bin/factory -h
