
[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.3.2"

[[constraint]]
  name = "github.com/onrik/logrus"
  version = "0.3.0"

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  version = "0.17.0"

[[constraint]]
  branch = "master"
  name = "github.com/factorysh/go-longrun"
