= Utilisation du client en ligne de commande

`factory` CLI est une application compilée, sans dépendance, disponible pour
différents OS.

Ce client permet d'intérragir avec les projets déployés sur votre usine logiciel factory.

== Pré requis

L'utilisation du client requiert:

- un agent ssh (reportez vous à la documentation de ssh-agent) gérant une clé
  ssh dont la clé publique a été uploader sur votre compte utilisateur gitlab.
  https://docs.gitlab.com/ce/ssh/README.html[Voir la documentation gitlab] pour
  plus d'information sur ce point.

- un https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html[token
  gitlab] avec, à minima, les scopes `api` et `read_registry`.

- de lancer la commande depuis un projet git hébergé sur gitlab. Ainsi certain
  paramètre sont déduis de votre .git (url du gitlab et non du projet)

== Options communes

Obtenir de l'aide, utilisez l'option `-h`

[source, shell]
----
$ factory -h
----

Vous pouvez obtenir l'aide d'une commande de la même manière:

[source, shell]
----
$ factory journal -h
----

L'option `-t` vous permet de passer votre token gitlab:

[source, shell]
----
$ factory -t votre_token ...
----

Vous pouvez aussi le définir dans l'environnement de votre shell pour ne pas
avoir à le repasser à chaque commande:

[source, shell]
----
$ export PRIVATE_TOKEN=votre_token
$ factory ...
----

Enfin, vous pouvez le stocker dans un fichier de configuration:

[source, shell]
----
$ echo "token: votre_token" > $HOME/.factory-cli.yaml
----


La plupart des commandes sont liées à un environnement (staging/production/etc.)
L'option `-e staging` indique que la commande agira sur l'environnement de staging.

[source, shell]
----
$ factory journal -e staging
----

== Afficher les informations du projet

Afficher les informations du projet courant:

[source, shell]
----
$ factory infos
----

Afficher aussi la liste des environnements du projet courant:

[source, shell]
----
$ factory infos --with-environments
$ factory infos -e
----

== Consultation des journaux systèmes

Factory regroupe et homogénéise diverses sources de logs pour des services
locaux ou distants.

La commande `factory journal` permets d'accéder et d'interroger le flot de logs
de ses applications. Il est possible d'accéder aux événements passés, mais
aussi de suivre le flot d'événements courants, en direct.


Pour accéder au journaux, les commandes disponibles sont les suivantes
(l'exemple utilise le serveur de préprod) :

Afficher les 10 dernières lignes de log

[source, shell]
----
$ factory journal -e staging
----

Afficher les 30 dernières lignes de log

[source, shell]
----
$ factory journal -e staging --lines -30
----

Afficher les 10 dernières lignes et suivre le flow

[source, shell]
----
$ factory journal -e staging --lines -10 --follow
----

Appliquer une regex sur les logs

[source, shell]
----
$ factory journal -e staging --lines -10 --follow --regexp "Handshake"
----

== Copier des fichiers

Un serveur sftp est à votre disposition.

Vous pouvez l'utiliser en mode interractif:

[source, shell]
----
$ factory volume -e staging sftp
----

Ou en mode non interractif, en passant vos commandes via l'entrée standard (STDIN).

Pousser un fichier:

[source, shell]
----
$ echo put test ./data/volume/test | factory volume -e staging sftp
----

Récupérer un fichier:

[source, shell]
----
$ echo get ./data/volume/test test | factory volume -e staging sftp
----

== Executer une commande au sein d'un conteneur

`factory exec` vous permets de lancer une commande au sein des conteneurs de vôtre projet.

Bash est la commande par défaut:

[source, shell]
----
$ factory container exec -e staging web
----

Mais vous pouvez en spécifier une:

[source, shell]
----
$ factory container exec -e staging web -- ls -l
----

`--` est utilisé pour passer les arguments au shell et non à `factory exec`.

== Récupérer un dump de base de donnée

La commande `factory dump` vous permets de récupérer un dump de base de données:

[source, shell]
----
$ factory container dump -e staging mysql
----

Le fichier est récupéré en local sous forme d'archive.


