name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull image
        run: docker pull bearstech/golang-dep
      - name: Build
        run: make docker-build CACHE=`pwd`/.cache
      - name: Tests
        run: make docker-test CACHE=`pwd`/.cache
      - name: Tests runjob
        run: make docker-test-runjob CACHE=`pwd`/.cache
      - name: Build binaries
        run: make docker-binaries CACHE=`pwd`/.cache
